# Generated by Django 4.0 on 2022-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_alter_alert_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
